name: Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: ["FA12", "FA2", "MIXED"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install Git
        run: sudo apt install git -y
      - name: Install modules
        run: yarn
      - name: Compile and test the contracts
        run: yarn compile && yarn test
        env:
          EXCHANGE_TOKEN_STANDARD: ${{ matrix.standard }}
          LIGO_VERSION: "0.26.0"
